# Generated by Django 3.1.3 on 2021-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='travelPoints',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
